### ISSUE TITLE
About suntan /sunplot

### ISSUE THREAD

**Issue by JacobZhao** [zyaj/suntans-general-vertical-coordinate#1]
hello,
I'm a new user of SUNTANS.
When I run the model, I meet a problem:
./sunplot --datadir= example/(some things)
it show X11/xlib.h not found.
And I check the user guide, it need /usr/X11R6
I installed X11 but it didn't showed 'X11R6'
Under /usr/include there is a X11 folder.

would u mind tell me how to solve this problem ?

Sincerely,
Zhao

**Comment by zyaj** [comment]
Hi, 
Are you using linux or mac? The Makefile provided is for Mac. I just uploaded a linux version 
If you are using a Mac, just change XINC/XLIBDIR to the directory of X11/include and X11/lib in your local machine.
Best,
Yun

**Comment by JacobZhao** [comment]
Thanks for your reply.
I'm using Mac and Ubuntu.
On Mac the original makefiles is ok. It can be made.
But after I try the example code
[ ./sunplot --datadir=../examples/cylinder/data]
it shows [Usage: ./sunplot [-np (numprocs), -2d, -n (time step), -k (vert level), -g, -m] ]
No display.
And this also happened on my ubuntu 16.04

Looking for your reply.

Yours,
Zhao

**Comment by zyaj** [comment]
Hi Zhao
Just check the codes on my latest mac. It works fine. 
It will be great if you can provide more details about the setup.
Yun

**Comment by JacobZhao** [comment]
Sorry for reply late Yun,
Now I be able to use suntans on my Mac and Ubuntu 16.04 correctly.
But when running on an ubuntu 18.04 LTS, it meet some problems.
I will upload error files on attachment.

Sincerely ,
Zhao
[归档.zip](https://github.com/zyaj/suntans-general-vertical-coordinate/files/2129991/default.zip)

**Comment by zyaj** [comment]
Hi Zhao
Actually we never run suntans in ubuntu 18.04. There may be some compile issue.
Please run in the old version first.

Thanks.
Yun

**Comment by JacobZhao** [comment]
Dear Yun,
OK , thanks for your patient answer. I'll try it on 16.04
I'll close this issue.
If there is any other question, I'll be in touch.

Sincerely,
Zhao
